name: Deploy to QA

on:
  push:
    branches:
      - devolpment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy Bundle to QA
        run: |
          # La CLI va lire directement DATABRICKS_HOST et DATABRICKS_TOKEN ci-dessous
          databricks bundle deploy -t qa
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_QA }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_QA }}
          