name: Deploy to QA

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh


      #- name: Sync Dev Volume to QA Volume
      #  run: |
      #    # 1. On liste les fichiers du Dev (nécessite DATABRICKS_HOST_DEV)
      #    # 2. On les copie vers la QA (nécessite DATABRICKS_HOST_QA)
      #    # Attention : C'est complexe car la CLI ne peut pas gérer deux hosts en une commande
      #    
      #    databricks fs cp -r dbfs:/Volumes/main_dev/default/mon_volume_entree dbfs:/Volumes/main_qa/default/mon_volume_entree

      - name: Transfer via Transit (Isolated)
        run: |
          # Créer un dossier temporaire en dehors de la racine du projet Git
          # pour éviter que la CLI ne détecte le fichier databricks.yml
          mkdir -p /tmp/databricks_transit
          
          echo "--- Downloading from DEV ---"
          # On lance la commande dans /tmp pour ignorer le bundle local
          cd /tmp && DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }} \
          DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }} \
          databricks fs cp -r dbfs:/Volumes/main_dev/default/mon_volume_entree ./databricks_transit
          
          echo "--- Uploading to QA ---"
          # On fait la même chose pour l'upload
          cd /tmp && DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_QA }} \
          DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_QA }} \
          databricks fs cp -r ./databricks_transit dbfs:/Volumes/main_qa/default/mon_volume_entree --overwrite
      